window.TechPulseData = {
  gravity: 1.65,
  videos: [
    {
      videoId: "F_tm2qxcUAI",
      topic: "YouTube Data API 自动化数据管道实战",
      category: "AI",
      channel: "Data Automation Lab",
      publishedHours: 5.5,
      views: 186000,
      likes: 9200,
      comments: 1480,
      summary: "这条技术分享拆解了如何围绕指定频道和关键词搭建 YouTube 数据看板。对 TechPulse 来说，它验证了 RSS 发现、API 精准同步和 Quota 控制这条路径的可行性，也适合作为后续工程实现的参考样例。",
      chapters: ["00:00 数据管道目标", "06:20 YouTube API 查询策略", "14:10 批量入库与可视化", "21:45 Quota 成本控制"],
      related: ["rss-pipeline", "quota-control"],
      tags: ["YouTube API", "Pipeline", "Quota"],
      quality: 92,
      status: "ready",
    },
    {
      videoId: "2ePf9rue1Ao",
      topic: "AI 编程智能体进入 IDE 主战场",
      category: "AI",
      channel: "AI Explained",
      publishedHours: 7.2,
      views: 312000,
      likes: 18000,
      comments: 2600,
      summary: "多个开发工具频道开始集中评测 IDE 内置智能体。核心看点不再只是补全速度，而是上下文窗口、工具调用、代码库检索、成本控制以及本地隐私。中文用户应重点关注团队协作和私有仓库接入能力。",
      chapters: ["01:12 Agent IDE 对比", "09:40 上下文窗口测试", "17:28 成本与隐私", "25:10 适合谁先用"],
      related: ["devin-ide", "cursor-agent"],
      tags: ["AI Agent", "IDE", "Coding"],
      quality: 88,
      status: "ready",
    },
    {
      videoId: "aqz-KE-bpKQ",
      topic: "MKBHD 新旗舰手机影像评测引发讨论",
      category: "Review",
      channel: "Marques Brownlee",
      publishedHours: 10.8,
      views: 1240000,
      likes: 76000,
      comments: 8100,
      summary: "MKBHD 的新旗舰评测把影像算法、续航和散热推到讨论中心。热度来自两部分：一是厂商宣传与真实体验之间的差距，二是 AI 修图在手机摄影中的边界。适合关注数码消费和产品定位的读者。",
      chapters: ["02:20 外观与屏幕", "08:05 相机算法", "15:32 续航压力测试", "23:18 购买建议"],
      related: ["phone-camera-ai", "flagship-review"],
      tags: ["MKBHD", "Phone", "Camera"],
      quality: 96,
      status: "review",
    },
    {
      videoId: "ysz5S6PUM-U",
      topic: "OpenAI 新模型发布后的开发者生态变化",
      category: "AI",
      channel: "OpenAI",
      publishedHours: 14.5,
      views: 860000,
      likes: 42000,
      comments: 5200,
      summary: "OpenAI 发布新模型后，开发者讨论集中在多模态能力、工具调用稳定性、推理成本以及企业数据边界。该话题会影响 AI 应用开发路线，也是中文开发者需要第一时间跟进的基础设施变化。",
      chapters: ["00:45 模型能力总览", "07:18 API 价格变化", "16:20 多模态演示", "29:00 企业部署边界"],
      related: ["openai-api", "model-release"],
      tags: ["OpenAI", "Model", "API"],
      quality: 94,
      status: "ready",
    },
    {
      videoId: "ScMzIvxBSi4",
      topic: "Linus Tech Tips 测试新一代 AI PC",
      category: "Devices",
      channel: "Linus Tech Tips",
      publishedHours: 18.4,
      views: 980000,
      likes: 39000,
      comments: 6100,
      summary: "LTT 对 AI PC 的测试把 NPU 跑分、真实软件适配和电池续航放在同一张表里。结论是硬件叙事已经领先于软件生态，短期更适合轻量本地推理和会议类功能，而非完整替代云端大模型。",
      chapters: ["03:00 NPU 是什么", "11:30 本地推理测试", "19:44 续航变化", "31:22 是否值得买"],
      related: ["ai-pc-benchmark", "npu-laptop"],
      tags: ["AI PC", "NPU", "Laptop"],
      quality: 87,
      status: "draft",
    },
    {
      videoId: "jNQXAC9IVRw",
      topic: "Anthropic 安全研究更新：AI Agent 权限边界",
      category: "AI",
      channel: "Anthropic",
      publishedHours: 21.6,
      views: 268000,
      likes: 13500,
      comments: 1900,
      summary: "Anthropic 的安全更新聚焦 Agent 使用工具时的权限边界、提示注入和审计记录。对计划上线自动化工作流的团队来说，这比模型榜单更重要，因为它直接决定 AI 能不能接触真实业务系统。",
      chapters: ["01:00 Agent 风险模型", "08:32 权限沙盒", "18:44 Prompt Injection", "27:15 企业审计"],
      related: ["agent-security", "prompt-injection"],
      tags: ["Anthropic", "Security", "Agent"],
      quality: 91,
      status: "ready",
    },
    {
      videoId: "kJQP7kiw5Fk",
      topic: "The Verge 追踪可穿戴 AI 设备真实体验",
      category: "Devices",
      channel: "The Verge",
      publishedHours: 9.3,
      views: 522000,
      likes: 21000,
      comments: 3900,
      summary: "可穿戴 AI 设备继续成为海外科技媒体关注点。The Verge 的体验强调了麦克风权限、全天候记录、电池和语音交互失败率。这个话题适合观察 AI 硬件从概念走向日常使用时的摩擦。",
      chapters: ["00:55 设备形态", "06:40 语音交互", "13:25 隐私问题", "20:08 产品结论"],
      related: ["ai-wearable", "humane-pin"],
      tags: ["Wearable", "AI Hardware", "Privacy"],
      quality: 84,
      status: "draft",
    },
    {
      videoId: "L_jWHffIx5E",
      topic: "Google Workspace AI 功能开始进入企业日常",
      category: "Platform",
      channel: "Google Workspace",
      publishedHours: 11.1,
      views: 354000,
      likes: 14400,
      comments: 1700,
      summary: "Google Workspace 的更新说明 AI 助手正在从演示走向办公流。重点能力包括文档自动总结、会议记录、表格分析和跨应用检索。中文企业用户需要关注权限、中文质量和既有流程迁移成本。",
      chapters: ["02:14 Docs 摘要", "09:10 Meet 记录", "15:18 Sheets 分析", "24:52 管理员控制台"],
      related: ["workspace-ai", "office-ai"],
      tags: ["Google", "Workspace", "Enterprise"],
      quality: 89,
      status: "ready",
    },
  ],
  channels: [
    { name: "OpenAI", type: "AI 科技先锋", description: "模型、API、多模态和开发者生态", weight: 1.35, status: "active", cadence: "Daily" },
    { name: "Anthropic", type: "AI 科技先锋", description: "AI 安全、Claude、Agent 权限边界", weight: 1.25, status: "active", cadence: "Daily" },
    { name: "Google Workspace", type: "AI 科技先锋", description: "办公 AI、企业协作和生产力工具", weight: 1.1, status: "active", cadence: "6h" },
    { name: "Andrej Karpathy", type: "AI 科技先锋", description: "AI 教学、深度学习和工程思考", weight: 1.2, status: "active", cadence: "Daily" },
    { name: "Two Minute Papers", type: "AI 科技先锋", description: "AI 论文、生成模型和研究进展", weight: 1.15, status: "active", cadence: "6h" },
    { name: "Marques Brownlee", type: "综合科技评测", description: "手机、消费电子和产品观点", weight: 1.3, status: "active", cadence: "2h" },
    { name: "Linus Tech Tips", type: "综合科技评测", description: "硬件测试、PC、服务器和实验", weight: 1.18, status: "active", cadence: "2h" },
    { name: "Unbox Therapy", type: "综合科技评测", description: "新品开箱、消费电子趋势", weight: 0.9, status: "watch", cadence: "6h" },
    { name: "Mrwhosetheboss", type: "综合科技评测", description: "手机横评、消费科技和体验", weight: 1.22, status: "active", cadence: "2h" },
    { name: "The Verge", type: "综合科技评测", description: "平台生态、硬件体验和科技文化", weight: 1.05, status: "active", cadence: "6h" },
    { name: "Dave2D", type: "综合科技评测", description: "笔记本、硬件设计和购买建议", weight: 1, status: "active", cadence: "6h" },
    { name: "Fireship", type: "开发者科技", description: "开发工具、框架和 AI 编程效率", weight: 1.16, status: "active", cadence: "6h" },
  ],
};

window.TechPulseUtils = {
  scoreVideo(video) {
    const gravity = window.TechPulseData.gravity;
    return Math.round((video.views + 5 * video.likes + 10 * video.comments) / Math.pow(video.publishedHours + 2, gravity));
  },
  formatNumber(value) {
    if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`;
    if (value >= 1000) return `${Math.round(value / 1000)}K`;
    return String(value);
  },
};
