window.TechPulseProducts = {
  generatedAt: "2026-07-11T05:45:00.000Z",
  products: [
    {
      id: "cursor",
      name: "Cursor",
      category: "AI Coding",
      tagline: "AI 原生 IDE，近期讨论集中在 Agent、MCP 和代码库理解能力。",
      signalScore: 92,
      signalTrend: "+18",
      sourceMix: { github: 28, community: 24, video: 31, freshness: 9 },
      evidence: ["GitHub 增长强", "HN 讨论活跃", "海外视频评测密集"],
      quickTake:
        "Cursor 已经从补全工具变成开发工作流入口。当前看点不是单次代码生成，而是它能否把 Agent、上下文检索和团队代码库权限做成稳定生产力。",
      bestFor: ["高频写代码的开发者", "AI coding 团队试点", "需要代码库问答的产品团队"],
      notFor: ["只需要轻量补全的用户", "对代码外传高度敏感的团队"],
      risks: ["价格敏感", "供应商锁定", "团队权限和隐私治理仍需评估"],
      github: { label: "核心仓库/生态", value: "高速增长", detail: "围绕 IDE、Agent 和插件生态形成持续讨论。" },
      community: { label: "社区观点", value: "正负混合", detail: "认可效率提升，同时担心成本、隐私和长期依赖。" },
      videos: ["sLYXRA5Ay9g", "0x4KRxmRGz4"],
      keywords: ["cursor", "ai ide", "agent", "mcp", "coding"],
    },
    {
      id: "claude-code",
      name: "Claude Code",
      category: "AI Agent",
      tagline: "Anthropic 面向终端和代码库任务的 Agent 工作流。",
      signalScore: 88,
      signalTrend: "+15",
      sourceMix: { github: 22, community: 29, video: 27, freshness: 10 },
      evidence: ["开发者实测多", "终端工作流关注高", "与 Cursor 形成对照"],
      quickTake:
        "Claude Code 的机会在于更接近工程师真实命令行环境。它不是 IDE 替代品，而是面向仓库理解、重构和多文件修改的 Agent 执行层。",
      bestFor: ["熟悉终端的开发者", "需要重构旧项目的团队", "Agent 工作流研究者"],
      notFor: ["偏可视化 IDE 用户", "非技术业务用户"],
      risks: ["执行边界", "成本可控性", "复杂项目的一致性"],
      github: { label: "开源生态", value: "周边工具增长", detail: "插件、脚本和工作流封装正在增多。" },
      community: { label: "社区观点", value: "偏正面", detail: "开发者关注它在大型仓库中的稳定性和可解释性。" },
      videos: ["m0F9Ar35WrA", "S82W3hWDvZA"],
      keywords: ["claude code", "anthropic", "agent", "terminal"],
    },
    {
      id: "lovable",
      name: "Lovable",
      category: "AI App Builder",
      tagline: "用自然语言生成应用原型，面向非工程用户和快速验证场景。",
      signalScore: 83,
      signalTrend: "+11",
      sourceMix: { github: 16, community: 23, video: 33, freshness: 11 },
      evidence: ["视频演示传播强", "创业者关注高", "与 Bolt/Replit 同赛道"],
      quickTake:
        "Lovable 的核心价值是降低从想法到可点击原型的门槛。它适合做 MVP 验证，但复杂业务逻辑、权限和长期维护仍需要工程能力接管。",
      bestFor: ["独立开发者", "产品经理", "早期创业验证"],
      notFor: ["复杂企业系统", "高安全要求项目"],
      risks: ["生成质量波动", "后期工程债", "同质化竞争"],
      github: { label: "技术生态", value: "外部集成增长", detail: "用户更关注生成后如何接数据库和部署。" },
      community: { label: "社区观点", value: "分化明显", detail: "非工程用户称赞速度，开发者更关注可维护性。" },
      videos: ["KwJwYIqDMLY", "4sexN3yE8xg"],
      keywords: ["lovable", "app builder", "no code", "mvp"],
    },
    {
      id: "mcp",
      name: "Model Context Protocol",
      category: "AI Infra",
      tagline: "让模型连接工具、数据源和业务系统的开放协议。",
      signalScore: 80,
      signalTrend: "+9",
      sourceMix: { github: 31, community: 21, video: 18, freshness: 10 },
      evidence: ["GitHub 生态扩张", "开发者教程增多", "Agent 工具链核心变量"],
      quickTake:
        "MCP 是 Agent 应用从演示走向可用的关键连接层。短期热度来自工具集成，长期价值取决于权限、安全审计和企业系统接入标准化。",
      bestFor: ["Agent 平台", "企业内部工具集成", "开发者工具团队"],
      notFor: ["只做普通聊天机器人的产品", "没有外部工具调用需求的应用"],
      risks: ["安全边界", "协议碎片化", "权限治理复杂"],
      github: { label: "开源生态", value: "快速扩张", detail: "Server、SDK、目录和示例项目持续增加。" },
      community: { label: "社区观点", value: "谨慎乐观", detail: "认可标准化价值，同时担忧权限和供应链风险。" },
      videos: ["sha3EL1ngN8", "KIp8PAU3oAI"],
      keywords: ["mcp", "model context protocol", "agent tools"],
    },
    {
      id: "perplexity",
      name: "Perplexity",
      category: "AI Search",
      tagline: "搜索、问答和内容发现融合的 AI 答案引擎。",
      signalScore: 76,
      signalTrend: "+6",
      sourceMix: { github: 8, community: 25, video: 26, freshness: 9 },
      evidence: ["产品争议高", "搜索体验被频繁对比", "商业化讨论升温"],
      quickTake:
        "Perplexity 的价值在于把搜索结果压缩成可读答案。风险也同样明显：内容版权、来源透明度和与传统搜索/浏览器入口的竞争。",
      bestFor: ["研究型搜索", "市场信息收集", "轻量竞品扫描"],
      notFor: ["需要原始文献逐条审阅的严肃研究", "强合规引用场景"],
      risks: ["版权争议", "事实准确性", "搜索入口竞争"],
      github: { label: "开源生态", value: "低相关", detail: "主要信号来自社区讨论和产品传播。" },
      community: { label: "社区观点", value: "争议活跃", detail: "效率提升和内容使用边界是主要争论点。" },
      videos: ["WZvd1tUreTY", "COTv_if0yPo"],
      keywords: ["perplexity", "ai search", "answer engine"],
    },
  ],
};
